x-dev-app-template: &dev-app-template
  restart: 'no'
  image: ghcr.io/dtcooper/tomato-server:dev
  volumes:
    - .:/app

services:
  app:
    <<: *dev-app-template
    ports:
      - "${DEBUG_APP_PORT:-8000}:8000"

  tasks:
    <<: *dev-app-template

  api:
    <<: *dev-app-template
    ports:
      - "${DEBUG_API_PORT:-8001}:8000"

  nginx:
    restart: 'no'
    volumes:
      - ./local-ca:/etc/local_ca
    environment:
      USE_LOCAL_CA: "${NGINX_DEBUG_MODE_ONLY_USE_LOCAL_CA:-0}"
      LOCAL_CA_ROOT_CERT_VALIDITY: 90  # 90 days instead of 30

  db:
    restart: 'no'
    ports:
      - "127.0.0.1:${DEBUG_DB_PORT:-5432}:5432"

  logs:
    restart: 'no'
    ports:
      - "127.0.0.1:${DEBUG_LOGS_PORT:-8002}:8000"
