x-dev-app-template: &dev-app-template
  restart: 'no'
  image: ghcr.io/dtcooper/tomato-server:dev
  volumes:
    - .:/app

services:
  app:
    <<: *dev-app-template
    ports:
      - 8000:8000

  tasks:
    <<: *dev-app-template

  db:
    restart: 'no'
    ports:
      - 127.0.0.1:5432:5432

  redis:
    restart: 'no'
    ports:
      - 127.0.0.1:6379:6379

  logs:
    restart: 'no'
    ports:
      - 127.0.0.1:9999:8000
