x-app-template: &app-template
  restart: always
  image: "ghcr.io/dtcooper/tomato-server:${TOMATO_VERSION:-latest}"
  depends_on:
    - db
  build:
    context: .
    args:
      - "DEBUG=${DEBUG:-0}"
  volumes:
    - ./.env:/.env
    - ./serve:/serve
    - huey_data:/huey

services:
  app:
    <<: *app-template

  tasks:
    <<: *app-template
    environment:
      __RUN_HUEY: 1

  api:
    <<: *app-template
    environment:
      __RUN_API: 1

  nginx:
    restart: always
    image: "ghcr.io/dtcooper/tomato-nginx:${TOMATO_VERSION:-latest}"
    build:
      context: nginx
    depends_on:
      - app
      - api
      - logs
    volumes:
      - ./serve:/serve:ro
      - nginx_secrets:/etc/letsencrypt
    environment:
      CERTBOT_EMAIL: "${CERTBOT_EMAIL:?CERTBOT_EMAIL needs to be set. See .env file.}"
      DOMAIN_NAME: "${DOMAIN_NAME:?DOMAIN_NAME needs to be set. See .env file.}"
      DEBUG: "${DEBUG:-0}"
    ports:
      - 80:80
      - 443:443

  db:
    restart: always
    image: pgautoupgrade/pgautoupgrade:17-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: postgres

  logs:
    restart: always
    image: amir20/dozzle:v8.6.0
    volumes:
      - "${DOCKER_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock"
    environment:
      DOZZLE_ADDR: ":8000"
      DOZZLE_BASE: "/server_logs"
      DOZZLE_HOSTNAME: "${DOMAIN_NAME}"
      DOZZLE_NO_ANALYTICS: "true"

volumes:
  nginx_secrets:
  postgres_data:
  huey_data:
