x-app-template: &app-template
  restart: always
  image: ghcr.io/dtcooper/tomato-server:latest
  depends_on:
    - db
    - redis
  build:
    context: .
    args:
      - "DEBUG=${DEBUG:-0}"
  volumes:
    - ./.env:/.env
    - ./serve:/serve

services:
  app:
    <<: *app-template

  tasks:
    <<: *app-template
    environment:
      - __RUN_HUEY=1

  db:
    restart: always
    image: postgres:15.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres

  redis:
    restart: always
    image: redis:7.0-alpine
    volumes:
      - redis_data:/data

  logs:
    restart: always
    image: amir20/dozzle:v4.10.8
    volumes:
      - "${DOCKER_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock"
    environment:
      - DOZZLE_ADDR=:8000
      - DOZZLE_BASE=/server-logs
      - "DOZZLE_HOSTNAME=${DOMAIN_NAME}"

volumes:
  postgres_data:
  redis_data:
