x-dev-app-template: &dev-app-template
  restart: 'no'
  image: ghcr.io/dtcooper/tomato-server:dev
  volumes:
    - .:/app

services:
  app:
    <<: *dev-app-template
    ports:
      - 8000:8000

  tasks:
    <<: *dev-app-template

  db:
    restart: 'no'
    ports:
      - 127.0.0.1:5432:5432

  redis:
    restart: 'no'
    ports:
      - 127.0.0.1:6379:6379

  nginx:
    restart: 'no'
    environment:
      - "USE_LOCAL_CA=${NGINX_USE_LOCAL_CA:-0}"
    volumes:
      - ./local-certificate-authority:/etc/local_ca
