x-app-template: &app-template
  restart: always
  image: ghcr.io/dtcooper/tomato-server:latest
  depends_on:
    - db
    - redis
    - minio
  build:
    context: .
    args:
      - "DEBUG=${DEBUG:-0}"
  volumes:
    - ./.env:/.env:ro
    - ../constants.json:/constants.json:ro
    - ./static:/static

services:
  app:
    <<: *app-template

  tasks:
    <<: *app-template
    environment:
      - __RUN_HUEY=1

  db:
    restart: always
    image: postgres:14.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres

  redis:
    restart: always
    image: redis:6.2-alpine
    volumes:
      - redis_data:/data

  nginx:
    restart: always
    image: jonasal/nginx-certbot:3.2
    depends_on:
      - app
      - minio
    volumes:
      - ./nginx.conf:/etc/nginx/templates/app.conf.template:ro
      - ./static:/static
      - nginx_secrets:/etc/letsencrypt
    environment:
      - "CERTBOT_EMAIL=${CERTBOT_EMAIL:?CERTBOT_EMAIL needs to be set. See .env file.}"
      - "DOMAIN_NAME=${DOMAIN_NAME:?DOMAIN_NAME needs to be set. See .env file.}"
    ports:
      - 80:80
      - 443:443

  minio:
    restart: always
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE
      - "MINIO_ROOT_PASSWORD=${SECRET_KEY}"
      - "MINIO_SERVER_URL=http://${DOMAIN_NAME}:9000/"
    image: quay.io/minio/minio:RELEASE.2022-09-17T00-09-45Z

volumes:
  minio_data:
  nginx_secrets:
  postgres_data:
  redis_data:
