services:
  nginx:
    restart: always
    image: jonasal/nginx-certbot:3.2-alpine
    depends_on:
      - app
      - logs
    volumes:
      - ./nginx.conf:/etc/nginx/templates/app.conf.template:ro
      - ./serve:/serve:ro
      - nginx_secrets:/etc/letsencrypt
    environment:
      - "CERTBOT_EMAIL=${CERTBOT_EMAIL:?CERTBOT_EMAIL needs to be set. See .env file.}"
      - "DOMAIN_NAME=${DOMAIN_NAME:?DOMAIN_NAME needs to be set. See .env file.}"
    ports:
      - 80:80
      - 443:443

volumes:
  nginx_secrets:
