x-dev-app-template: &dev-app-template
  restart: 'no'
  image: ghcr.io/dtcooper/tomato-server:dev
  volumes:
    - .:/app

services:
  app:
    <<: *dev-app-template
    ports:
      - "${DEBUG_APP_PORT:-8000}:8000"

  tasks:
    <<: *dev-app-template

  db:
    restart: 'no'
    ports:
      - "127.0.0.1:${DEBUG_DB_PORT:-5432}:5432"

  redis:
    restart: 'no'
    ports:
      - "127.0.0.1:${DEBUG_REDIS_PORT:-6379}:6379"

  logs:
    restart: 'no'
    ports:
      - "127.0.0.1:${DEBUG_LOGS_PORT:-8001}:8000"
