services:
  app:
    restart: always
    image: ghcr.io/dtcooper/tomato-server:latest
    depends_on:
      - db
      - redis
    build:
      context: .
      args:
        - "DEBUG=${DEBUG:-0}"
    volumes:
      - ./.env:/.env:ro
      - ../constants.json:/constants.json:ro
      - ./serve:/serve

  db:
    restart: always
    image: library/postgres:14.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres

  redis:
    restart: always
    image: library/redis:6.2-alpine
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
