[tool.poetry]
name = "tomato"
version = "0.0.1-dev0"
description = "Tomato Radio Automation Server"
authors = ["David Cooper <david.cooper@burningman.org>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.11"
django = "^4.2.3"
django-cleanup = "^8.0.0"
# For error messages at top of page, once constance > 2.9.1, can pin again
django-constance = {git = "https://github.com/jazzband/django-constance.git", rev = "554dac04"}
django-environ = "^0.10.0"
django-dirtyfields = "^1.9.2"
django-file-form = "^3.5.2"
django-user-messages = "^1.0.0"
gunicorn = "^21.2.0"
huey = "^2.4.5"
starlette = "^0.30.0"

[tool.poetry.group.server.dependencies]
django-redis = {extras = ["hiredis"], version = "^5.3.0"}
psycopg = "^3.1.9"
uvicorn = {extras = ["standard"], version = "^0.23.1"}
wait-for-it = "^2.2.2"

[tool.poetry.group.dev.dependencies]
black = "^23.7.0"
django-debug-toolbar = "^4.1.0"
django-extensions = "^3.2.3"
flake8 = "^6.0.0"
ipdb = "^0.13.13"
ipython = "^8.14.0"
isort = "^5.12.0"
watchdog = {extras = ["watchmedo"], version = "^3.0.0"}

[tool.poetry.group.standalone.dependencies]
django-redis = "^5.3.0"
uvicorn = "^0.23.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ['py310']
exclude = '/migrations/'
preview = true

[tool.isort]
multi_line_output = 3
lines_after_imports = 2
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 120
force_sort_within_sections = true
sections = ['FUTURE', 'STDLIB', 'THIRDPARTY', 'STARLETTE', 'DJANGO', 'DJANGOTHIRDPARTY', 'FIRSTPARTY', 'LOCALFOLDER']
known_starlette = ['starlette']
known_django = ['django']
known_djangothirdparty = ['constance', 'dirtyfields', 'django_redis', 'django_file_form', 'environ', 'huey.contrib', 'user_messages']
skip = ['migrations']
