[tool.poetry]
name = "tomato"
version = "0.0.1-dev0"
description = "Tomato Radio Automation Server"
authors = ["David Cooper <david.cooper@burningman.org>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.11"
django = "^4.1.7"
django-cleanup = "^7.0.0"
# For error messages at top of page, once constance > 2.9.1, can pin again
django-constance = {git = "https://github.com/jazzband/django-constance.git", rev = "master", extras = ["database"]}
django-dirtyfields = "^1.9.1"
django-environ = "^0.9.0"
django-file-form = "^3.4.4"
django-user-messages = "^1.0.0"
huey = "^2.4.5"
pybase62 = "^0.6.0"
python-dotenv = "^0.21.1"
requests = "^2.28.1"
wait-for-it = "^2.2.1"

[tool.poetry.group.server.dependencies]
django-redis = {extras = ["hiredis"], version = "^5.2.0"}
gunicorn = "^20.1.0"
psycopg2 = "^2.9.5"

[tool.poetry.group.dev.dependencies]
black = "^23.1.0"
django-debug-toolbar = "^3.8.1"
django-extensions = "^3.2.1"
flake8 = "^6.0.0"
ipdb = "^0.13.11"
ipython = "^8.10.0"
isort = "^5.12.0"
watchdog = {extras = ["watchmedo"], version = "^2.2.1"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ['py310']
exclude = '/migrations/'
preview = true

[tool.isort]
multi_line_output = 3
lines_after_imports = 2
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 120
force_sort_within_sections = true
sections = ['FUTURE', 'STDLIB', 'THIRDPARTY', 'DJANGO', 'DJANGOTHIRDPARTY', 'FIRSTPARTY', 'LOCALFOLDER']
known_django = ['django']
known_djangothirdparty = ['constance', 'dirtyfields', 'django_redis', 'django_file_form', 'environ', 'huey.contrib', 'user_messages']
skip = ['migrations']
