[tool.poetry]
name = "tomato"
version = "0.0.1-dev0"
description = "Tomato Radio Automation Server"
authors = ["David Cooper <david.cooper@burningman.org>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.11"
django = "^5.0.6"
django-admin-notice = "^3.0.1"
django-constance = "^3.1.0"
django-dirtyfields = "^1.9.3"
django-environ = "^0.11.2"
django-file-form = "^3.7.0"
django-pgtrigger = "^4.11.1"
django-user-messages = "^1.0.0"
gunicorn = "^22.0.0"
huey = "^2.5.1"
psycopg = "^3.2.1"
python-dotenv = "^1.0.1"
schema = "^0.7.7"
starlette = "^0.37.2"
uvicorn = {extras = ["standard"], version = "^0.30.1"}
wait-for-it = "^2.2.2"

[tool.poetry.group.dev.dependencies]
black = "^24.4.2"
django-debug-toolbar = "^4.4.2"
django-extensions = "^3.2.3"
flake8 = "^7.1.0"
ipdb = "^0.13.13"
ipython = "^8.26.0"
isort = "^5.13.2"
pywatchman = "^2.0.0"
watchdog = {extras = ["watchmedo"], version = "^4.0.1"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ["py312"]
preview = true
enable-unstable-feature = [
    "multiline_string_handling", "string_processing", "wrap_long_dict_values_in_parens",
    "hex_codes_in_unicode_sequences", "hug_parens_with_braces_and_square_brackets"
]

[tool.isort]
multi_line_output = 3
lines_after_imports = 2
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 120
force_sort_within_sections = true
combine_as_imports = true
sections = ['FUTURE', 'STDLIB', 'THIRDPARTY', 'DJANGO', 'STARLETTE', 'DJANGOTHIRDPARTY', 'FIRSTPARTY', 'LOCALFOLDER']
known_starlette = ['starlette', 'uvicorn']
known_django = ['django']
known_djangothirdparty = ['constance', 'dirtyfields', 'django_file_form', 'environ', 'huey.contrib', 'safedelete', 'user_messages']
skip = ['migrations']
