[tool.poetry]
name = "tomato"
version = "0.0.1-dev0"
description = "Tomato Radio Automation Server"
authors = ["David Cooper <david.cooper@burningman.org>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.11"
django = "^4.2.5"
django-admin-notice = "^2.1.0"
django-constance = "^3.1.0"
django-dirtyfields = "^1.9.2"
django-environ = "^0.11.2"
django-file-form = "^3.5.3"
django-redis = {extras = ["hiredis"], version = "^5.3.0"}
# For hard_delete_soft_deleted action, once safedelete > 1.3.2, can pin again
django-safedelete = {git = "https://github.com/makinacorpus/django-safedelete.git"}
django-user-messages = "^1.0.0"
gunicorn = "^21.2.0"
huey = "^2.5.0"
psycopg = "^3.1.12"
python-dotenv = "^1.0.0"
starlette = "^0.31.1"
uvicorn = {extras = ["standard"], version = "^0.23.2"}
wait-for-it = "^2.2.2"

[tool.poetry.group.dev.dependencies]
black = "^23.9.1"
django-debug-toolbar = "^4.2.0"
django-extensions = "^3.2.3"
flake8 = "^6.1.0"
ipdb = "^0.13.13"
ipython = "^8.16.0"
isort = "^5.12.0"
watchdog = {extras = ["watchmedo"], version = "^3.0.0"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ['py310']
exclude = '/migrations/'
preview = true

[tool.isort]
multi_line_output = 3
lines_after_imports = 2
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 120
force_sort_within_sections = true
sections = ['FUTURE', 'STDLIB', 'THIRDPARTY', 'STARLETTE', 'DJANGO', 'DJANGOTHIRDPARTY', 'FIRSTPARTY', 'LOCALFOLDER']
known_starlette = ['starlette']
known_django = ['django']
known_djangothirdparty = ['constance', 'dirtyfields', 'django_redis', 'django_file_form', 'environ', 'huey.contrib', 'safedelete', 'user_messages']
skip = ['migrations']
