[tool.poetry]
name = "tomato"
version = "0.0.1-dev0"
description = "Tomato Radio Automation Server"
authors = ["David Cooper <david.cooper@burningman.org>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
base58 = "^2.1.1"
Django = "^4.1.1"
django-cleanup = "^6.0.0"
django-constance = {extras = ["redis"], version = "^2.9.1"}
django-dirtyfields = "^1.8.2"
django-environ = "^0.9.0"
django-file-form = "^3.4.1"
django-redis = {extras = ["hiredis"], version = "^5.2.0"}
django-user-messages = "^0.8.0"
gunicorn = "^20.1.0"
huey = "^2.4.3"
psycopg2 = "^2.9.3"
watchdog = {extras = ["watchmedo"], version = "^2.1.9"}

[tool.poetry.group.dev.dependencies]
black = "^22.8.0"
django-debug-toolbar = "^3.6.0"
django-extensions = "^3.2.1"
flake8 = "^5.0.4"
ipdb = "^0.13.9"
ipython = "^8.5.0"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ['py310']
exclude = '/migrations/'
preview = true

[tool.isort]
multi_line_output = 3
lines_after_imports = 2
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 120
force_sort_within_sections = true
sections = ['FUTURE', 'STDLIB', 'THIRDPARTY', 'DJANGO', 'DJANGOTHIRDPARTY', 'FIRSTPARTY', 'LOCALFOLDER']
known_django = ['django']
known_djangothirdparty = ['constance', 'dirtyfields', 'django_redis', 'django_file_form', 'environ', 'huey.contrib', 'user_messages']
skip = ['migrations']
