name: Build and push
description: Build and push docker containers

inputs:
  container:
    description: Container name
    required: true
  tag:
    description: Container tag name
    required: true
  token:
    description: GitHub token
    required: true
  no-cache:
    description: Do not use cache when building
    required: false
    default: 'false'
  build-args:
    description: List of build-time variables
    required: false
  platforms:
    description: Container build platforms
    required: false
    default: 'linux/amd64,linux/arm64'

runs:
  using: composite
  steps:
    -
      name: Set variables
      id: vars
      shell: bash
      run: |
        USERNAME="$(echo "$GITHUB_REPOSITORY_OWNER" | tr '[:upper:]' '[:lower:]')"
        echo "CACHE_TAG=ghcr.io/${USERNAME}/tomato-build-cache:${{ inputs.container }}-${{ inputs.tag }}" >> "$GITHUB_ENV"
        echo "REPO=ghcr.io/${USERNAME}/tomato-${{ inputs.container }}" >> "$GITHUB_ENV"
        echo "USERNAME=${USERNAME}" >> "$GITHUB_ENV"
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Login to Github Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ env.USERNAME }}
        password: ${{ inputs.token }}
    -
      name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        pull: true
        platforms: ${{ inputs.platforms }}
        context: ./${{ inputs.container }}/
        tags: ${{ env.REPO }}:${{ inputs.tag }}
        build-args: ${{ inputs.build-args }}
        cache-from: ${{ inputs.no-cache == 'false' && format('type=registry,ref={0}', env.CACHE_TAG) || '' }}
        cache-to: ${{ inputs.no-cache == 'false' && format('type=registry,ref={0},mode=max', env.CACHE_TAG) || '' }}
