# Generated by Django 5.2.7 on 2025-10-14 13:53

import datetime
import dirtyfields.dirtyfields
import django.utils.timezone
import tomato.models.asset
import tomato.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "begin",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text="Custom begin date help text",
                        null=True,
                        verbose_name="begin air date",
                    ),
                ),
                (
                    "end",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text="Custom end date help text",
                        null=True,
                        verbose_name="end air date",
                    ),
                ),
                (
                    "file",
                    tomato.models.base.AudioFileField(
                        max_length=120, upload_to=tomato.models.asset.asset_upload_to, verbose_name="audio file"
                    ),
                ),
                ("original_filename", models.CharField(max_length=120)),
                ("pre_process_md5sum", models.BinaryField(default=None, max_length=16, null=True)),
                ("md5sum", models.BinaryField(default=None, max_length=16, null=True)),
                ("filesize", models.BigIntegerField(default=-1)),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "Pending processing"), (1, "Processing"), (2, "Ready")],
                        default=0,
                        help_text="All assets will be processed after uploading.",
                    ),
                ),
                ("duration", models.DurationField(default=datetime.timedelta(0))),
                ("comment", models.TextField(blank=True, help_text="Any private comments about a particular asset")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.localtime, verbose_name="created at"
                    ),
                ),
                ("created_by", models.EmailField(db_index=True, max_length=254, verbose_name="created by")),
                (
                    "name",
                    models.CharField(help_text="TODO name help text", max_length=120, unique=True, verbose_name="name"),
                ),
                (
                    "submit_status",
                    models.SmallIntegerField(
                        choices=[(0, "todo 0"), (1, "todo 1"), (2, "todo 2")],
                        default=0,
                        help_text="TODO submit status help text.",
                    ),
                ),
            ],
            options={
                "verbose_name": "user submission",
                "db_table": "submissions",
                "ordering": ("-created_at",),
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
