name: Version
description: Get Tomato build Version
outputs:
  version:
    description: "Version"
    value: ${{ steps.vars.outputs.version }}
  protocol:
    description: "Protocol"
    value: ${{ steps.vars.outputs.protocol }}

runs:
  using: composite
  steps:
    -
      name: Full checkout to compute version
      if: github.ref_type != 'tag'
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    -
      name: Export version
      id: vars
      shell: bash
      run: |
        if [ "${GITHUB_REF_TYPE}" == 'tag' ]; then
          VERSION="${GITHUB_REF_NAME}"
        else
          VERSION="r$(git rev-list --count HEAD).$(git rev-parse --short=8 HEAD)"
        fi
        PROTOCOL="$(jq -r .protocol_version server/constants.json)"

        echo "Setting Tomato version to ${VERSION} [protocol=${PROTOCOL}]"
        echo "version=${VERSION}" >> "$GITHUB_OUTPUT"
        echo "protocol=${PROTOCOL}" >> "$GITHUB_OUTPUT"
