name: Version
description: Get Tomato build Version
outputs:
  version:
    description: "Random number"
    value: ${{ steps.vars.outputs.version }}

runs:
  using: composite
  steps:
    -
      name: Full checkout to compute version
      if: github.ref_type != 'tag'
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    -
      name: Export version
      id: vars
      shell: bash
      run: |
        if [ "${GITHUB_REF_TYPE}" == 'tag' ]; then
          VERSION="${GITHUB_REF_NAME}"
        else
          VERSION="r$(git rev-list --count HEAD).$(git rev-parse --short=8 HEAD)"
        fi

        echo "Setting Tomato version to ${VERSION}"
        echo "version=${VERSION}" >> "$GITHUB_OUTPUT"
