# Generated by Django 4.2.3 on 2023-07-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tomato", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="enable_client_logs",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "Use this to enable or disable client logging for this account. In general you'll want to keep this"
                    " enabled, but for test accounts you may not want to pollute the client logs."
                ),
                verbose_name="Write client logs",
            ),
        ),
    ]
