# Generated by Django 4.2.4 on 2023-08-10 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tomato", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientlogentry",
            name="type",
            field=models.CharField(
                choices=[
                    ("internal_error", "Internal client error"),
                    ("login", "Logged in or reconnected"),
                    ("logout", "Logged out"),
                    ("overdue", "Playing of stop set overdue"),
                    ("played_asset", "Played an audio asset"),
                    ("played_stopset", "Played an entire stop set"),
                    ("skipped_asset", "Skipped (or played a partial) audio asset"),
                    ("skipped_stopset", "Skipped (or played a partial) stop set."),
                    ("waited", "Waited"),
                    ("unspecified", "Unspecified"),
                ],
                default="unspecified",
                max_length=15,
            ),
        ),
    ]
