# Generated by Django 4.2.4 on 2023-08-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tomato", "0002_finalize_clientlogentry_types"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientlogentry",
            options={
                "ordering": ("-created_at", "-id"),
                "verbose_name": "client log entry",
                "verbose_name_plural": "client log entries",
            },
        ),
        migrations.AddField(
            model_name="rotator",
            name="enabled",
            field=models.BooleanField(
                default=True,
                help_text=(
                    "If unselected, rotator is <strong>completely disabled</strong> regardless of its inclusion in a"
                    " stop set."
                ),
                verbose_name="enabled",
            ),
        ),
    ]
