# Generated by Django 4.2.5 on 2023-09-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tomato", "0004_single_play_rotators"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="deleted",
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="deleted_by_cascade",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
