# Generated by Django 4.2.5 on 2023-09-08 23:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tomato", "0004_single_play_rotators"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="asset",
            options={
                "ordering": ("-created_at",),
                "permissions": [("configure_live_clients", "Can configure currently connected Desktop clients")],
                "verbose_name": "audio asset",
            },
        ),
    ]
