# Generated by Django 4.2.5 on 2023-09-30 23:11

import datetime
import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tomato.models.asset
import tomato.models.base


class Migration(migrations.Migration):
    dependencies = [
        ("tomato", "0004_single_play_rotators"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetAlternate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created at")),
                (
                    "file",
                    tomato.models.base.AudioFileField(max_length=120, upload_to=tomato.models.asset.asset_upload_to),
                ),
                ("original_filename", models.CharField(max_length=120)),
                ("pre_process_md5sum", models.BinaryField(default=None, max_length=16, null=True)),
                ("md5sum", models.BinaryField(default=None, max_length=16, null=True)),
                ("filesize", models.BigIntegerField(default=-1)),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "Pending processing"), (1, "Processing"), (2, "Ready")],
                        default=0,
                        help_text="All assets will be processed after uploading.",
                    ),
                ),
                ("duration", models.DurationField(default=datetime.timedelta(0))),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alternates",
                        to="tomato.asset",
                        verbose_name="alternate for asset",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "audio asset alternate",
                "db_table": "asset_alternates",
                "ordering": ("id",),
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
    ]
