# Generated by Django 4.2.7 on 2023-11-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("constance", "0002_migrate_from_old_table"),
        ("tomato", "0005_asset_alternates_save_asset_files"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetRotatorsProxy",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("tomato.asset_rotators",),
        ),
        migrations.CreateModel(
            name="ConstanceProxy",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("constance.constance",),
        ),
        migrations.AddField(
            model_name="clientlogentry",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name="IP address"),
        ),
        migrations.AlterField(
            model_name="asset",
            name="rotators",
            field=models.ManyToManyField(
                blank=True,
                db_table="asset_rotators",
                help_text="Rotators that this asset will be included in.",
                related_name="assets",
                to="tomato.rotator",
                verbose_name="rotators",
            ),
        ),
    ]
