# Generated by Django 5.0.7 on 2024-07-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tomato", "0006_pg_notify_triggers"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="archived",
            field=models.BooleanField(
                default=False,
                help_text="Archived models will not show in the desktop client. Think of archive as 'soft delete'.",
                verbose_name="archived",
            ),
        ),
    ]
