# Generated by Django 5.0.7 on 2024-07-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tomato", "0007_asset_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="rotator",
            name="evenly_cycle",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "If selected, rotator cycles through its assets evenly <strong><em>completely"
                    " ignoring</em></strong> their weight. In short, this completely bypasses the randomization"
                    " algorithm and instead picks every asset within this rotator <strong>once</strong> before"
                    " resetting back to the first asset."
                ),
                verbose_name="evenly cycle",
            ),
        ),
    ]
