# Generated by Django 5.0.7 on 2024-08-08 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tomato", "0008_rotator_evenly_cycle"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="asset",
            options={
                "ordering": ("-created_at",),
                "permissions": [
                    ("configure_live_clients", "Can configure live desktop clients"),
                    ("export_import", "Can manage (import/export/delete all) asset data"),
                ],
                "verbose_name": "audio asset",
            },
        ),
    ]
