# Generated by Django 5.0.9 on 2024-09-13 18:15

import django.contrib.admin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("tomato", "0009_extra_perms"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServerLogEntry",
            fields=[],
            options={
                "verbose_name": "admin log entry",
                "verbose_name_plural": "admin logs",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("admin.logentry",),
            managers=[
                ("objects", django.contrib.admin.models.LogEntryManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name="assetalternate",
            options={
                "ordering": ("id",),
                "verbose_name": "audio asset alternate",
                "verbose_name_plural": "asset alternates",
            },
        ),
        migrations.AlterModelOptions(
            name="clientlogentry",
            options={
                "ordering": ("-created_at", "-id"),
                "verbose_name": "client log entry",
                "verbose_name_plural": "client logs",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="email address"),
        ),
    ]
