# Generated by Django 5.2.5 on 2025-08-18 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tomato", "0010_user_emails"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="comment",
            field=models.TextField(blank=True, help_text="Any private comments about a particular asset"),
        ),
        migrations.AddField(
            model_name="assetalternate",
            name="comment",
            field=models.TextField(blank=True, help_text="Any private comments about a particular asset"),
        ),
        migrations.AlterField(
            model_name="rotator",
            name="stopsets",
            field=models.ManyToManyField(
                related_name="rotators",
                through="tomato.StopsetRotator",
                through_fields=("rotator", "stopset"),
                to="tomato.stopset",
                verbose_name="stop set",
            ),
        ),
    ]
