# Generated by Django 5.2.6 on 2025-09-18 21:02

import tomato.models.user
from django.db import migrations


def set_individual_status(apps, schema_editor):
    cursor = schema_editor.connection.cursor()
    cursor.execute("""
        SELECT DISTINCT event_object_table, trigger_name
        FROM information_schema.triggers
        WHERE trigger_name LIKE 'pgtrigger_%'
    """)
    triggers = list(cursor)

    for table_name, trigger_name in triggers:
        cursor.execute(f"DROP TRIGGER {trigger_name} ON {table_name}")
        cursor.execute(f"DROP FUNCTION {trigger_name}")

    cursor.execute("DROP FUNCTION IF EXISTS _pgtrigger_should_ignore")


class Migration(migrations.Migration):
    dependencies = [
        ("tomato", "0011_asset_comment"),
    ]

    operations = [
        migrations.RunPython(set_individual_status, migrations.RunPython.noop),
        migrations.DeleteModel(
            name="ConstanceProxy",
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", tomato.models.user.TomatoUserManager()),
            ],
        ),
    ]
