copyright: Copyright &copy; 2022 <a href="https://jew.pizza" target="_blank">David Cooper</a> &amp; <a href="https://bmir.org" target="_blank">Burning Man Information Radio</a>
dev_addr: 127.0.0.1:8888
docs_dir: .
edit_uri: ""
repo_name: dtcooper/tomato
repo_url: https://github.com/dtcooper/tomato
site_name: Tomato Radio Automation
site_url: https://dtcooper.github.io/tomato/
strict: true

nav:
  - index.md
  - client.md
  - server.md
  - concepts.md
  - license.md

extra_css:
  - assets/extra.css

extra_javascript:
  - assets/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js?config=AM_CHTML

plugins:
  - search
  - same-dir

theme:
  name: material
  favicon: assets/favicon.svg
  font:
    text: Space Grotesk
    code: Space Mono  # ligatures disabled in extra.css
  icon:
    logo: material/radio
    repo: fontawesome/brands/github
  features:
    - content.tabs.link
    - navigation.expand
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - search.highlight
    - search.suggest
    - toc.integrate
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: pink
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: pink
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.snippets:
      base_path: [ "../LICENSE" ]
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: "\u2190"

extra:
  generator: false
