[tool.poetry]
name = "tomato-docs"
version = "1.0.0"
description = ""
authors = ["David Cooper <david.cooper@burningman.org>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
mkdocs = "1.3.1"
mkdocs-same-dir = "^0.1.1"
mkdocs-material = "^8.5.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
