[tool.poetry]
name = "tomato-docs"
version = "1.0.0"
description = ""
authors = ["David Cooper <david.cooper@burningman.org>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
mkdocs = "^1.4.2"
mkdocs-macros-plugin = "^0.7.0"
mkdocs-material = "^9.1.1"
mkdocs-same-dir = "^0.1.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
