# General
VERSION = "0.4.0"
PRODUCT_NAME = "Tomato Button Box"
NEXT_BOOT_OVERRIDES = ("debug", "debug_messages_over_transport", "midi_transport", "hid_transport")

# Kindly assigned by pid.codes (https://pid.codes/1209/7111/)
USB_VENDOR_ID = 0x1209
USB_PRODUCT_ID = 0x7111

# Button commands
MIDI_BTN_CTRL = 0x10
BTN_PRESSED = 1
BTN_RELEASED = 0

# LED commands
MIDI_LED_CTRL = 0x11
LED_OFF = 0
LED_ON = 1
LED_FLASH = 2
LED_PULSATE_SLOW = 3
LED_PULSATE_MEDIUM = 4
LED_PULSATE_FAST = 5
LED_RANGE = (LED_OFF, LED_ON, LED_FLASH, LED_PULSATE_SLOW, LED_PULSATE_MEDIUM, LED_PULSATE_FAST)
LED_RANGE_MIN = min(LED_RANGE)
LED_RANGE_MAX = max(LED_RANGE)

# HID reports
BUTTON_REPORT_ID = 1
LED_REPORT_ID = 2
DATA_REQUEST_REPORT_ID = 3
DATA_RESPONSE_REPORT_ID = 4
DATA_RESPONSE_REPORT_LENGTH = 63

# HID actions
DATA_REQUEST_PING = 0
DATA_REQUEST_STATS = 1
DATA_REQUEST_SIMULATE_PRESS = 2
DATA_REQUEST_SIMULATE_RELEASE = 3
DATA_REQUEST_RESTART = 4
DATA_REQUEST_RESET = 5
DATA_REQUEST_FLASH = 6
DATA_REQUEST_NEXT_BOOT_OVERRIDE_START = 7
DATA_REQUEST_NEXT_BOOT_OVERRIDE_END = DATA_REQUEST_NEXT_BOOT_OVERRIDE_START + len(NEXT_BOOT_OVERRIDES) - 1

# System Exclusive (MIDI)
SYSEX_NON_COMMERCIAL = 0x7D
SYSEX_PREFIX = b"%c!T~" % SYSEX_NON_COMMERCIAL  # 0x7D is the non-commercial sysex prefix
SYSEX_PREFIX_LEN = len(SYSEX_PREFIX)
SYSEX_MAX_LEN = 128
