from config import LED_PULSATE_PERIOD_FAST, LED_PULSATE_PERIOD_MEDIUM, LED_PULSATE_PERIOD_SLOW


# General
VERSION = "0.1.3"
PRODUCT_NAME = "Tomato Button Box"

# Button commands
MIDI_BTN_CTRL = 0x10
BTN_PRESSED = 0x7F
BTN_RELEASED = 0

# LED commands
MIDI_LED_CTRL = 0x11
LED_OFF = 0
LED_ON = 1
LED_FLASH = 2
LED_PULSATE_PERIODS = (LED_PULSATE_PERIOD_SLOW, LED_PULSATE_PERIOD_MEDIUM, LED_PULSATE_PERIOD_FAST)
LED_PULSATE_RANGE_START = 3
LED_PULSATE_RANGE_END = LED_PULSATE_RANGE_START + len(LED_PULSATE_PERIODS) - 1

# System Exclusive
SYSEX_NON_COMMERCIAL = 0x7D
SYSEX_PREFIX = b"%c!T~" % SYSEX_NON_COMMERCIAL  # 0x7D is the non-commercial sysex prefix
SYSEX_PREFIX_LEN = len(SYSEX_PREFIX)
SYSEX_STATS_PREFIX = b"S~"
SYSEX_MAX_LEN = 128
