name: Build & deploy server container (test)

on:
  push:
    branches:
      - main
    paths:
      - .github/actions/docker-build-push/action.yml
      - .github/actions/version/action.yml
      - .github/workflows/build-deploy-on-push.yml
      - server/**
  workflow_dispatch:

concurrency:
  group: docker-build
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Build container
    strategy:
      matrix:
        include:
          -
            container: server
            tag: dev
          -
            container: server
            tag: latest
          -
            container: nginx
            tag: latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Get version
        id: version
        if: matrix.container == 'server'
        uses: ./.github/actions/version
      -
        name: Build container (server)
        uses: ./.github/actions/docker-build-push
        if: matrix.container == 'server'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          container: server
          tag: ${{ matrix.tag }}
          build-args: |
            DEBUG=${{ matrix.tag == 'dev' && '1' || '0' }}
            TOMATO_VERSION=${{ steps.version.outputs.version }}
      -
        name: Build container (nginx)
        uses: ./.github/actions/docker-build-push
        if: matrix.container == 'nginx'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          container: nginx
          context: server/nginx
          tag: ${{ matrix.tag }}


  deploy:
    runs-on: ubuntu-22.04
    name: Deploy
    needs: [build]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Deploy containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          fingerprint: ${{ secrets.SSH_FINGERPRINT }}
          script: ${{ secrets.DEPLOY_TEST_SCRIPT_PATH }}
