name: Build client

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: client-build
  cancel-in-progress: true

jobs:
  build-macos:
    runs-on: macos-11
    name: Build macOS client
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Setup Node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      -
        name: Build packages
        shell: bash
        run: |
          mkdir -p ~/.ssh
          chmod 0700 ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 0600 ~/.ssh/id_ed25519
          echo "${{ secrets.SSH_KNOWN_HOST }}" >> ~/.ssh/known_hosts
          cd client
          npm install
          npm run build
          npx electron-forge make --arch arm64 --platform darwin
          npx electron-forge make --arch x64 --platform darwin
          mv -v out/make/zip/darwin/arm64/*.zip tomato-preview-macos-m1.zip
          mv -v out/make/zip/darwin/x64/*.zip tomato-preview-macos-intel.zip
          scp -P ${{ secrets.SSH_PORT}} tomato-preview-macos-m1.zip tomato-preview-macos-intel.zip "${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:${{ secrets.CLIENT_BUILD_UPLOAD_DIR }}"

  build-win32:
    runs-on: windows-2022
    name: Build Windows client
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Setup Node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      -
        name: Build packages
        shell: bash
        run: |
          mkdir -p ~/.ssh
          chmod 0700 ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 0600 ~/.ssh/id_ed25519
          echo "${{ secrets.SSH_KNOWN_HOST }}" >> ~/.ssh/known_hosts
          cd client
          npm config set script-shell $(which bash)
          npm install
          npm run build
          npx electron-forge make --arch x64 --platform win32
          mv -v out/make/zip/win32/x64/*.zip tomato-preview-windows.zip
          scp -P ${{ secrets.SSH_PORT}} tomato-preview-windows.zip "${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:${{ secrets.CLIENT_BUILD_UPLOAD_DIR }}"

  build-linux:
    runs-on: ubuntu-20.04
    name: Build Linux client
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Setup Node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      -
        name: Build packages
        shell: bash
        run: |
          mkdir -p ~/.ssh
          chmod 0700 ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 0600 ~/.ssh/id_ed25519
          echo "${{ secrets.SSH_KNOWN_HOST }}" >> ~/.ssh/known_hosts
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libudev-dev
          cd client
          npm install
          npm run build
          npx electron-forge make --arch x64 --platform linux
          mv -v out/make/deb/x64/*.deb tomato-preview-linux_amd64.deb
          mv -v out/make/rpm/x64/*.rpm tomato-preview-linux.x86_64.rpm
          scp -P ${{ secrets.SSH_PORT}} tomato-preview-linux_amd64.deb tomato-preview-linux.x86_64.rpm "${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:${{ secrets.CLIENT_BUILD_UPLOAD_DIR }}"
