name: Build client

on:
  push:
    branches:
      - main
    paths:
      - client/**
      - server/constants.json
  workflow_dispatch:

concurrency:
  group: client-build
  cancel-in-progress: true

jobs:
  build-macos:
    runs-on: macos-11
    name: Build macOS client
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Setup Node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      -
        name: Build & upload package
        shell: bash
        run: |
          cd client
          npm clean-install
          npm run build
          npx electron-forge make --arch universal --platform darwin
          mv -v out/make/zip/darwin/universal/*.zip ../tomato-preview-macos.zip
      -
        name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: tomato-preview-build-macos
          path: tomato-preview-macos.zip

  build-win32:
    runs-on: windows-2022
    name: Build Windows client
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Setup Node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      -
        name: Build & upload package
        shell: bash
        run: |
          cd client
          npm config set script-shell $(which bash)
          npm clean-install
          npm run build
          npx electron-forge make --arch x64 --platform win32
          mv -v out/make/zip/win32/x64/*.zip ../tomato-preview-windows.zip
      -
        name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: tomato-preview-build-win32
          path: tomato-preview-windows.zip

  build-linux-debian:
    runs-on: ubuntu-22.04
    name: Build Linux client (Debian/Ubuntu)
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Setup Node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      -
        name: Build & upload package
        shell: bash
        run: |
          cd client
          npm clean-install
          npm run build
          npx electron-forge make --arch x64 --platform linux
          mv -v out/make/deb/x64/*.deb ../tomato-preview-linux_amd64.deb
      -
        name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: tomato-preview-build-linux-debian
          path: tomato-preview-linux_amd64.deb

  build-linux-arch:
    runs-on: ubuntu-22.04
    name: Build Linux client (Arch)
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Setup rootless Docker
        uses: ScribeMD/rootless-docker@0.2.2
      -
        name: Build & upload package
        shell: bash
        # nodejs-lts-hydrogen = Node v18
        run: |
          docker run --rm -v "$PWD:/build" -w /build/client/scripts/arch archlinux:base-devel sh -c 'pacman -Syu --noconfirm nodejs-lts-hydrogen && env EUID=1 makepkg -s --noconfirm'
          mv client/scripts/arch/*.pkg.tar.zst tomato-preview-linux-x86_64.pkg.tar.zst
      -
        name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: tomato-preview-build-linux-arch
          path: tomato-preview-linux-x86_64.pkg.tar.zst

  tag:
    runs-on: ubuntu-22.04
    name: Tag preview release
    needs: [build-macos, build-win32, build-linux-debian, build-linux-arch]
    steps:
      -
        name: Download build artifact (macOS)
        uses: actions/download-artifact@v3
        with:
          name: tomato-preview-build-macos
      -
        name: Download build artifact (Windows)
        uses: actions/download-artifact@v3
        with:
          name: tomato-preview-build-win32
      -
        name: Download build artifact (Linux, Debian)
        uses: actions/download-artifact@v3
        with:
          name: tomato-preview-build-linux-debian
      -
        name: Download build artifact (Linux, Arch)
        uses: actions/download-artifact@v3
        with:
          name: tomato-preview-build-linux-arch
      -
        uses: mxschmitt/action-tmate@v3
