name: Publish docs

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/docs.yml
      - docs/**
      - server/tomato/settings.py
      - LICENSE
  workflow_dispatch:

concurrency:
  group: docs

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Publish
    env:
      POETRY_VERSION: 2.1.3
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          # Get a full clone so there's a local copy of gh-pages to commit to
          fetch-depth: 0
      -
        name: Setup Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      -
        name: Deploy docs
        run: |
          curl -sSL https://install.python-poetry.org | python -
          cd docs
          poetry install
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          poetry run mkdocs gh-deploy
