name: Publish docs

on:
  push:
    branches:
      - main
    paths:
      - docs/**
      - server/tomato/settings.py
      - LICENSE
  workflow_dispatch:

concurrency:
  group: docs

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Publish
    env:
      POETRY_VERSION: 1.4.2
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          # Get a full clone so there's a local copy of gh-pages to commit to
          fetch-depth: 0
      -
        name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      -
        name: Deploy docs
        run: |
          curl -sSL https://install.python-poetry.org | python -
          cd docs
          poetry install
          git config user.name 'Docs Deploy'
          git config user.email 'docs-deploy@users.noreply.github.com'
          poetry run mkdocs gh-deploy
